freeproxy_list:
  - SOCKS4:
      type: socks4
      speed: 5000
      file: freeproxy_socks4.txt
  - SOCKS5:
      type: socks5
      speed: 5000
      file: freeproxy_socks5.txt
  - anonymity:
      speed: 5000
      file: freeproxy_anonymity.txt
      anonymity: high

merge_list:
  - freeproxy_all.txt:
    - freeproxy_socks4.txt
    - freeproxy_socks5.txt
    - freeproxy_anonymity.txt
